# Generated by Django 5.1.15 on 2026-06-13 19:13

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Oczekuje'), ('processing', 'Przetwarzanie'), ('done', 'Gotowe'), ('failed', 'Błąd')], default='pending', max_length=20)),
                ('mode', models.CharField(choices=[('fast', 'Szybki (CPU)'), ('quality', 'Jakość (GPU/chmura)')], default='fast', max_length=20)),
                ('full_text', models.TextField(blank=True)),
                ('searchable_pdf', models.FileField(blank=True, null=True, upload_to='searchable/%Y/%m/')),
                ('doc_type', models.CharField(blank=True, choices=[('faktura', 'Faktura'), ('umowa', 'Umowa'), ('pismo_sadowe', 'Pismo sądowe'), ('pismo_urzedowe', 'Pismo urzędowe'), ('paragon', 'Paragon'), ('oferta', 'Oferta'), ('korespondencja', 'Korespondencja'), ('inne', 'Inne')], max_length=20)),
                ('doc_date', models.DateField(blank=True, null=True)),
                ('doc_number', models.CharField(blank=True, max_length=120)),
                ('counterparty', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('summary', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('extraction_error', models.TextField(blank=True)),
                ('indexed', models.BooleanField(default=False)),
                ('indexing_error', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField(default=1)),
                ('chunk_index', models.PositiveIntegerField(default=0)),
                ('text', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.document')),
            ],
            options={
                'ordering': ['document', 'chunk_index'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('text', models.TextField(blank=True)),
                ('source', models.CharField(default='ocr', max_length=20)),
                ('engine_name', models.CharField(blank=True, max_length=50)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='documents.document')),
            ],
            options={
                'ordering': ['document', 'page_number'],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['doc_type'], name='documents_d_doc_typ_4a1a00_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['doc_date'], name='documents_d_doc_dat_b03c6a_idx'),
        ),
        migrations.AddIndex(
            model_name='chunk',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='chunk_embedding_hnsw', opclasses=['vector_cosine_ops']),
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('document', 'page_number')},
        ),
    ]
