# Generated by Django 5.1.15 on 2026-06-18 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_polish_search'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('key', models.SlugField(max_length=60)),
                ('field_type', models.CharField(choices=[('text', 'Tekst'), ('number', 'Liczba'), ('date', 'Data')], default='text', max_length=10)),
                ('prompt', models.TextField(help_text='Instrukcja dla AI: co dokładnie wyodrębnić.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'key'), name='uniq_owner_field_key')],
            },
        ),
    ]
